uart:
  tx_pin: GPIOx
  rx_pin: GPIOy
  baud_rate: 2400
  rx_buffer_size: 1024

sensor:

text_sensor:

smartmeter:
  key: "<SMARTMETER_KEY>"
  voltage_l1:
    name: "Spannung L1"
  voltage_l2:
    name: "Spannung L2"
  voltage_l3:
    name: "Spannung L3"
  current_l1:
    name: "Strom L1"
  current_l2:
    name: "Strom L2"
  current_l3:
    name: "Strom L3"
  power_consumption:
    name: "Verbrauchsleistung"
  power_production:
    name: "Erzeugerleistung"
  power_factor:
    name: "Leistungsfaktor"
  energy_consumption:
    name: "Energieverbrauch"
  energy_production:
    name: "Energieerzeugung"
  reactive_energy_consumption:
    name: "Blinkenergieverbrauch"
  reactive_energy_production:
    name: "Blindenergieerzeugung"
  timestamp:
    name: "Zeit"
  meter_number:
    name: "Zählernummer"

time:
  - platform: homeassistant
    id: homeassistant_time
